import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { CheckCircle, ArrowRight, BarChart3, Zap, Target, ChevronRight } from "lucide-react"
import { FeatureAnimation } from "@/components/feature-animation"
import { SignalDemo } from "@/components/signal-demo"
import { WorkflowDemo } from "@/components/workflow-demo"
import { HomeBackgroundAnimation } from "@/components/home-background-animation"

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen">
      <HomeBackgroundAnimation />

      {/* Hero Section */}
      <section className="py-20 px-4 relative z-10">
        <div className="container mx-auto text-center">
          <h1 className="text-4xl md:text-6xl font-bold mb-6">
            AI-Powered <span className="text-green-500">Forex Signals</span>
          </h1>
          <p className="text-xl md:text-2xl text-gray-300 mb-10 max-w-3xl mx-auto">
            Get real-time trading signals with precise entry points, take profits, and stop losses generated by our
            advanced AI algorithm.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button asChild size="lg" className="text-lg">
              <Link href="/register">Start Free Trial</Link>
            </Button>
            <Button asChild variant="outline" size="lg" className="text-lg">
              <Link href="/login">Login</Link>
            </Button>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16 px-4 bg-gray-900/50 relative z-10">
        <div className="container mx-auto">
          <h2 className="text-3xl font-bold text-center mb-12">Why Choose InseparableFX?</h2>
          <div className="grid md:grid-cols-3 gap-8">
            <Card className="bg-gray-800/50 border-gray-700 overflow-hidden group hover:border-green-500/50 transition-all duration-300">
              <CardContent className="pt-6 pb-6">
                <div className="rounded-full bg-green-500/10 w-12 h-12 flex items-center justify-center mb-4 group-hover:bg-green-500/20 transition-all duration-300">
                  <BarChart3 className="h-6 w-6 text-green-500" />
                </div>
                <h3 className="text-xl font-bold mb-2 group-hover:text-green-400 transition-all duration-300">
                  AI-Powered Analysis
                </h3>
                <p className="text-gray-300 mb-4">
                  Our advanced AI algorithms analyze market data in real-time to generate accurate trading signals.
                </p>
                <div className="space-y-2 mb-4">
                  <div className="flex items-start">
                    <ChevronRight className="h-5 w-5 text-green-500 mr-2 shrink-0" />
                    <span className="text-sm text-gray-300">Neural networks trained on historical market data</span>
                  </div>
                  <div className="flex items-start">
                    <ChevronRight className="h-5 w-5 text-green-500 mr-2 shrink-0" />
                    <span className="text-sm text-gray-300">Pattern recognition across multiple timeframes</span>
                  </div>
                  <div className="flex items-start">
                    <ChevronRight className="h-5 w-5 text-green-500 mr-2 shrink-0" />
                    <span className="text-sm text-gray-300">Sentiment analysis from global financial sources</span>
                  </div>
                </div>
                <div className="h-[150px] bg-gray-900/50 rounded-md overflow-hidden">
                  <FeatureAnimation type="ai-analysis" />
                </div>
              </CardContent>
            </Card>

            <Card className="bg-gray-800/50 border-gray-700 overflow-hidden group hover:border-blue-500/50 transition-all duration-300">
              <CardContent className="pt-6 pb-6">
                <div className="rounded-full bg-blue-500/10 w-12 h-12 flex items-center justify-center mb-4 group-hover:bg-blue-500/20 transition-all duration-300">
                  <Target className="h-6 w-6 text-blue-500" />
                </div>
                <h3 className="text-xl font-bold mb-2 group-hover:text-blue-400 transition-all duration-300">
                  Precise Entry Points
                </h3>
                <p className="text-gray-300 mb-4">
                  Get exact entry points, take profit levels (TP1, TP2), and stop loss levels for each trade with
                  confidence scores.
                </p>
                <div className="space-y-2 mb-4">
                  <div className="flex items-start">
                    <ChevronRight className="h-5 w-5 text-blue-500 mr-2 shrink-0" />
                    <span className="text-sm text-gray-300">Optimized risk-reward ratios for every signal</span>
                  </div>
                  <div className="flex items-start">
                    <ChevronRight className="h-5 w-5 text-blue-500 mr-2 shrink-0" />
                    <span className="text-sm text-gray-300">Multiple take profit targets for maximum flexibility</span>
                  </div>
                  <div className="flex items-start">
                    <ChevronRight className="h-5 w-5 text-blue-500 mr-2 shrink-0" />
                    <span className="text-sm text-gray-300">Strategic stop loss placement to minimize risk</span>
                  </div>
                </div>
                <div className="h-[150px] bg-gray-900/50 rounded-md overflow-hidden">
                  <FeatureAnimation type="entry-points" />
                </div>
              </CardContent>
            </Card>

            <Card className="bg-gray-800/50 border-gray-700 overflow-hidden group hover:border-purple-500/50 transition-all duration-300">
              <CardContent className="pt-6 pb-6">
                <div className="rounded-full bg-purple-500/10 w-12 h-12 flex items-center justify-center mb-4 group-hover:bg-purple-500/20 transition-all duration-300">
                  <Zap className="h-6 w-6 text-purple-500" />
                </div>
                <h3 className="text-xl font-bold mb-2 group-hover:text-purple-400 transition-all duration-300">
                  Real-Time Updates
                </h3>
                <p className="text-gray-300 mb-4">
                  Receive instant notifications when new signals are generated or when take profit/stop loss levels are
                  hit.
                </p>
                <div className="space-y-2 mb-4">
                  <div className="flex items-start">
                    <ChevronRight className="h-5 w-5 text-purple-500 mr-2 shrink-0" />
                    <span className="text-sm text-gray-300">Instant push notifications for new signals</span>
                  </div>
                  <div className="flex items-start">
                    <ChevronRight className="h-5 w-5 text-purple-500 mr-2 shrink-0" />
                    <span className="text-sm text-gray-300">Live updates on signal performance</span>
                  </div>
                  <div className="flex items-start">
                    <ChevronRight className="h-5 w-5 text-purple-500 mr-2 shrink-0" />
                    <span className="text-sm text-gray-300">Market news alerts that impact your trades</span>
                  </div>
                </div>
                <div className="h-[150px] bg-gray-900/50 rounded-md overflow-hidden">
                  <FeatureAnimation type="real-time" />
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="py-20 px-4">
        <div className="container mx-auto">
          <h2 className="text-3xl font-bold text-center mb-4">How It Works</h2>
          <p className="text-xl text-gray-300 text-center mb-12 max-w-3xl mx-auto">
            Our AI-powered platform analyzes market data and delivers precise trading signals in real-time
          </p>

          <div className="relative">
            <WorkflowDemo />
          </div>
        </div>
      </section>

      {/* Signal Demo Section */}
      <section className="py-20 px-4 bg-gray-900/50">
        <div className="container mx-auto">
          <h2 className="text-3xl font-bold text-center mb-4">Live Signal Demo</h2>
          <p className="text-xl text-gray-300 text-center mb-12 max-w-3xl mx-auto">
            See how our AI generates accurate trading signals with precise entry, take profit, and stop loss levels
          </p>

          <div className="max-w-4xl mx-auto">
            <SignalDemo />
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section className="py-16 px-4">
        <div className="container mx-auto">
          <h2 className="text-3xl font-bold text-center mb-12">Simple, Transparent Pricing</h2>
          <div className="max-w-md mx-auto">
            <Card className="bg-gradient-to-br from-gray-800 to-gray-900 border-gray-700">
              <CardContent className="pt-6">
                <div className="text-center mb-6">
                  <h3 className="text-2xl font-bold mb-2">Daily Subscription</h3>
                  <div className="flex items-center justify-center">
                    <span className="text-4xl font-bold">$1</span>
                    <span className="text-gray-400 ml-2">/ day</span>
                  </div>
                </div>

                <div className="space-y-4 mb-6">
                  <div className="flex items-start">
                    <CheckCircle className="h-5 w-5 text-green-500 mr-2 mt-0.5" />
                    <span>Real-time forex signals</span>
                  </div>
                  <div className="flex items-start">
                    <CheckCircle className="h-5 w-5 text-green-500 mr-2 mt-0.5" />
                    <span>Precise entry, TP1, TP2, and SL levels</span>
                  </div>
                  <div className="flex items-start">
                    <CheckCircle className="h-5 w-5 text-green-500 mr-2 mt-0.5" />
                    <span>Major forex pairs, metals, and indices</span>
                  </div>
                  <div className="flex items-start">
                    <CheckCircle className="h-5 w-5 text-green-500 mr-2 mt-0.5" />
                    <span>Interactive charts and analysis</span>
                  </div>
                  <div className="flex items-start">
                    <CheckCircle className="h-5 w-5 text-green-500 mr-2 mt-0.5" />
                    <span>Cancel anytime, no commitment</span>
                  </div>
                </div>

                <div className="mb-4">
                  <p className="text-center text-sm text-gray-400 mb-2">Payment Methods</p>
                  <div className="flex justify-center gap-4">
                    <div className="flex items-center justify-center w-10 h-10 bg-blue-500/10 rounded-full">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="20"
                        height="20"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        className="text-blue-500"
                      >
                        <path d="M7 11l5-7" />
                        <path d="M21 11V6a2 2 0 0 0-2-2h-4l-5 7" />
                        <path d="M3 7v5a2 2 0 0 0 2 2h10" />
                        <path d="M16 16a2 2 0 0 0-2 2" />
                        <path d="M13 18h4" />
                        <path d="M19 18a2 2 0 0 0 2-2v-5" />
                      </svg>
                    </div>
                    <div className="flex items-center justify-center w-10 h-10 bg-yellow-500/10 rounded-full">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="20"
                        height="20"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        className="text-yellow-500"
                      >
                        <path d="M3 3h18v18H3z" />
                        <path d="m16 10-4 4-4-4" />
                      </svg>
                    </div>
                    <div className="flex items-center justify-center w-10 h-10 bg-gray-500/10 rounded-full">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="20"
                        height="20"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        className="text-gray-400"
                      >
                        <rect width="20" height="14" x="2" y="5" rx="2" />
                        <line x1="2" x2="22" y1="10" y2="10" />
                      </svg>
                    </div>
                  </div>
                </div>

                <Button asChild className="w-full">
                  <Link href="/register">
                    Start Free 24h Trial <ArrowRight className="ml-2 h-4 w-4" />
                  </Link>
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
    </div>
  )
}

